name: Deploy docs

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build library
        run: pnpm build
      - name: Build docs
        run: cd sites/docs && pnpm build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: sites/docs/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
